apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skidpdf-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: skidpdf
        tier: frontend
    spec:
      containers:
      - name: skidpdf-frontend
        image: gcr.io/kubetest-mindbody/skidpdf:instrumented_v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
